let date = new Date();
console.log(date.toDateString());
console.log(date.toTimeString());
console.log(date.toLocaleString());
console.log(date.getTime());
console.log(date.getFullYear());
console.log(date.getDay());
console.log(date.getMonth());
console.log(date.getDate());
console.log(date.getTimezoneOffset());
console.log(date.getHours());
